name: 'Shopify Dynamic Theme Id'
description: 'Get the theme ID of a Shopify store based on the branch name'
author: 'mattyfours'

inputs:
  variables:
    description: 'Environment Variables String Object'
    required: true
    default: '{}'

  token:
    description: 'Shopify Token'
    required: true

  store:
    description: 'Shopify Store'
    required: true

  branch:
    description: 'Branch Name'
    required: true

outputs:
  branchThemeId:
    description: 'Shopify theme ID'

runs:
  using: 'node20'
  main: 'dist/index.js'
