name: Continuous Integration

on:
  pull_request:
    branches: [main, feature/*, hotfix/*, develop/*]
  push:
    branches: [main, feature/*, hotfix/*, develop/*]

  run-name: Testing Action

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [Action Test]
    environment: ${{ matrix.environment }}
    env:
      SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
      SHOPIFY_FLAG_STORE: "${{ vars.SHOPIFY_FLAG_STORE }}"

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          variables: "${{ toJson(vars) }}"
          token: "${{ env.SHOPIFY_CLI_THEME_TOKEN }}"
          store: "${{ env.SHOPIFY_FLAG_STORE }}"
          branch: "${{ github.ref_name }}"

